# Generated by Django 6.0.4 on 2026-04-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position']},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('status', 'position')},
        ),
    ]
